### ISSUE TITLE
No found Local Pipeline. 

### ISSUE THREAD

**Issue by rodriguesfas** [CogComp/cogcomp-nlpy#106]
I would like help with Local Pipeline, I get the following error when I try to play the initial experiment.

INFO:ccg_nlpy.pipeline_config:Using local pipeline
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Traceback (most recent call last):
  File "/home/rodriguesfas/Workspace/Text-Mining/Tool_NLP/CogComp/example-02.py", line 5, in <module>
    pipeline = local_pipeline.LocalPipeline()
  File "/home/rodriguesfas/anaconda3/envs/text_minning/lib/python2.7/site-packages/ccg_nlpy/local_pipeline.py", line 62, in__init__
    self.pipeline = self.PipelineFactory.buildPipelineWithAllViews(self.Boolean(True))
  File "jnius/jnius_export_class.pxi", line 906, in jnius.JavaMultipleMethod.__call__
  File "jnius/jnius_export_class.pxi", line 637, in jnius.JavaMethod.__call__
  File "jnius/jnius_export_class.pxi", line 803, in jnius.JavaMethod.call_staticmethod
  File "jnius/jnius_utils.pxi", line 93, in jnius.check_exception
JavaException: JVM exception occurred: Index: 0, Size: 0

**Comment by danyaljj** [comment]
What is the snippet you use to run the code?

**Comment by rodriguesfas** [comment]
The code example I am trying to execute is as follows:

# Basic Local Pipeline
from ccg_nlpy import local_pipeline
pipeline = local_pipeline.LocalPipeline()
# constructor declaration: LocalPipeline()
document = [ ["Hi", "!"], ["How", "are", "you", "?"] ]
doc = pipeline.doc(document, pretokenized=True)
print doc

**Comment by danyaljj** [comment]
Can you try this please? 

document = "Hi how are you?" 
doc = pipeline.doc(document)

**Comment by nitishgupta** [comment]
Want to make sure if you used this command to download the models. 
``` python -m ccg_nlpy download ```

**Comment by rodriguesfas** [comment]
exclude, and redo the steps, without success. So for you is the local pipeline running? Here for me, the Remote pipeline works correctly, the problem is in the local papeline :(

**Comment by nitishgupta** [comment]
Yes, the local pipeline works correctly. I suggest you uninstall ccg_nlpy, re-install, and re-download the models. I tried it on my end, and it works.

**Comment by rodriguesfas** [comment]
Worked, thank you!
could you tell me the complete documentation to use with pyhton?
