### ISSUE TITLE
can't find and can't download several files. And as a result can't use SRL_VERB

### ISSUE THREAD

**Issue by haijun-ucsd** [CogComp/cogcomp-nlpy#126]
C:\Users\haijunxia\Desktop>python ccg_pipline.py
INFO:ccg_nlpy.pipeline_config:Using local pipeline
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [0.7 sec].
Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [1.0 sec].
INFO:ccg_nlpy.local_pipeline:pipeline has been set up
Local Untokenized Text
['Hello', ',', 'how', 'are', 'you', '.', 'I', 'am', 'doing', 'fine', '.']
Local Tokenized Text
['Hello', ',', 'how', 'are', 'you', '.', 'I', 'am', 'doing', 'fine', '.']
Local Untokenized SRL
Downloading the folder from datastore . . .
                GroupId: readonly.org.cogcomp.gazetteers
                ArtifactId: 1.6/gazetteers.zip
augmentedGroupId: readonly.org.cogcomp.gazetteers
versionedFileName: 1.6/gazetteers.zip
zippedFileName: C:\Users\haijunxia\.cogcomp-datastore\tmp\1.6\gazetteers.zip
java.net.ConnectException: Failed to connect to smaug.cs.illinois.edu/192.17.58.151:8080
        at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:139)
        at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:108)
        at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.squareup.okhttp.Call.getResponse(Call.java:286)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
        at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
        at com.squareup.okhttp.Call.execute(Call.java:80)
        at io.minio.MinioClient.execute(MinioClient.java:826)
        at io.minio.MinioClient.executeHead(MinioClient.java:1018)
        at io.minio.MinioClient.statObject(MinioClient.java:1154)
        at io.minio.MinioClient.getObject(MinioClient.java:1343)
        at org.cogcomp.Datastore.getDirectory(Datastore.java:556)
        at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.init(TreeGazetteers.java:72)
        at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.<init>(TreeGazetteers.java:51)
        at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.GazetteersFactory.init(GazetteersFactory.java:54)
        at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readAndLoadConfig(Parameters.java:274)
        at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readConfigAndLoadExternalData(Parameters.java:56)
        at edu.illinois.cs.cogcomp.ner.NERAnnotator.initialize(NERAnnotator.java:111)
        at edu.illinois.cs.cogcomp.annotation.Annotator.doInitialize(Annotator.java:126)
        at edu.illinois.cs.cogcomp.annotation.Annotator.lazyAddView(Annotator.java:201)
        at edu.illinois.cs.cogcomp.annotation.Annotator.getView(Annotator.java:167)
        at edu.illinois.cs.cogcomp.pipeline.main.SentencePipeline.processBySentence(SentencePipeline.java:112)
        at edu.illinois.cs.cogcomp.pipeline.main.SentencePipeline.addView(SentencePipeline.java:88)
        at edu.illinois.cs.cogcomp.pipeline.main.SentencePipeline.addView(SentencePipeline.java:78)
java.io.FileNotFoundException: C:\Users\haijunxia\.cogcomp-datastore\tmp\1.6\gazetteers.zip (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at org.cogcomp.ZipHelper.unZipIt(ZipHelper.java:71)
        at org.cogcomp.Datastore.getDirectory(Datastore.java:585)
        at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.init(TreeGazetteers.java:72)
        at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.<init>(TreeGazetteers.java:51)
        at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.GazetteersFactory.init(GazetteersFactory.java:54)
        at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readAndLoadConfig(Parameters.java:274)
        at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readConfigAndLoadExternalData(Parameters.java:56)
        at edu.illinois.cs.cogcomp.ner.NERAnnotator.initialize(NERAnnotator.java:111)
        at edu.illinois.cs.cogcomp.annotation.Annotator.doInitialize(Annotator.java:126)
        at edu.illinois.cs.cogcomp.annotation.Annotator.lazyAddView(Annotator.java:201)
        at edu.illinois.cs.cogcomp.annotation.Annotator.getView(Annotator.java:167)
        at edu.illinois.cs.cogcomp.pipeline.main.SentencePipeline.processBySentence(SentencePipeline.java:112)
        at edu.illinois.cs.cogcomp.pipeline.main.SentencePipeline.addView(SentencePipeline.java:88)
        at edu.illinois.cs.cogcomp.pipeline.main.SentencePipeline.addView(SentencePipeline.java:78)
zippedFileName: C:\Users\haijunxia\.cogcomp-datastore\tmp\1.6\gazetteers.zip
path: C:\Users\haijunxia\.cogcomp-datastore\readonly.org.cogcomp.gazetteers\1.6\gazetteers
artifactId: gazetteers
java.io.FileNotFoundException: C:\Users\haijunxia\.cogcomp-datastore\readonly.org.cogcomp.gazetteers\1.6\gazetteers\gazetteers\gazetteers-list.txt (The system cannot find the path specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.init(TreeGazetteers.java:73)
        at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.TreeGazetteers.<init>(TreeGazetteers.java:51)
        at edu.illinois.cs.cogcomp.ner.ExpressiveFeatures.GazetteersFactory.init(GazetteersFactory.java:54)
        at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readAndLoadConfig(Parameters.java:274)
        at edu.illinois.cs.cogcomp.ner.LbjTagger.Parameters.readConfigAndLoadExternalData(Parameters.java:56)
        at edu.illinois.cs.cogcomp.ner.NERAnnotator.initialize(NERAnnotator.java:111)
        at edu.illinois.cs.cogcomp.annotation.Annotator.doInitialize(Annotator.java:126)
        at edu.illinois.cs.cogcomp.annotation.Annotator.lazyAddView(Annotator.java:201)
        at edu.illinois.cs.cogcomp.annotation.Annotator.getView(Annotator.java:167)
        at edu.illinois.cs.cogcomp.pipeline.main.SentencePipeline.processBySentence(SentencePipeline.java:112)
        at edu.illinois.cs.cogcomp.pipeline.main.SentencePipeline.addView(SentencePipeline.java:88)
        at edu.illinois.cs.cogcomp.pipeline.main.SentencePipeline.addView(SentencePipeline.java:78)
Downloading the folder from datastore . . .
                GroupId: readonly.edu.illinois.cs.cogcomp.ner
                ArtifactId: 4.0/ner-model-enron-conll-all-data.zip
augmentedGroupId: readonly.edu.illinois.cs.cogcomp.ner
versionedFileName: 4.0/ner-model-enron-conll-all-data.zip
zippedFileName: C:\Users\haijunxia\.cogcomp-datastore\tmp\4.0\ner-model-enron-conll-all-data.zip
java.net.ConnectException: Failed to connect to smaug.cs.illinois.edu/192.17.58.151:8080
        at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:139)
        at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:108)
        at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.squareup.okhttp.Call.getResponse(Call.java:286)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
        at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
        at com.squareup.okhttp.Call.execute(Call.java:80)
        at io.minio.MinioClient.execute(MinioClient.java:826)
        at io.minio.MinioClient.executeHead(MinioClient.java:1018)
        at io.minio.MinioClient.statObject(MinioClient.java:1154)
        at io.minio.MinioClient.getObject(MinioClient.java:1343)
        at org.cogcomp.Datastore.getDirectory(Datastore.java:556)
        at edu.illinois.cs.cogcomp.ner.ModelLoader.load(ModelLoader.java:103)
        at edu.illinois.cs.cogcomp.ner.NERAnnotator.initialize(NERAnnotator.java:115)
        at edu.illinois.cs.cogcomp.annotation.Annotator.doInitialize(Annotator.java:126)
        at edu.illinois.cs.cogcomp.annotation.Annotator.lazyAddView(Annotator.java:201)
        at edu.illinois.cs.cogcomp.annotation.Annotator.getView(Annotator.java:167)
        at edu.illinois.cs.cogcomp.pipeline.main.SentencePipeline.processBySentence(SentencePipeline.java:112)
        at edu.illinois.cs.cogcomp.pipeline.main.SentencePipeline.addView(SentencePipeline.java:88)
        at edu.illinois.cs.cogcomp.pipeline.main.SentencePipeline.addView(SentencePipeline.java:78)
java.io.FileNotFoundException: C:\Users\haijunxia\.cogcomp-datastore\tmp\4.0\ner-model-enron-conll-all-data.zip (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at org.cogcomp.ZipHelper.unZipIt(ZipHelper.java:71)
        at org.cogcomp.Datastore.getDirectory(Datastore.java:585)
        at edu.illinois.cs.cogcomp.ner.ModelLoader.load(ModelLoader.java:103)
        at edu.illinois.cs.cogcomp.ner.NERAnnotator.initialize(NERAnnotator.java:115)
        at edu.illinois.cs.cogcomp.annotation.Annotator.doInitialize(Annotator.java:126)
        at edu.illinois.cs.cogcomp.annotation.Annotator.lazyAddView(Annotator.java:201)
        at edu.illinois.cs.cogcomp.annotation.Annotator.getView(Annotator.java:167)
        at edu.illinois.cs.cogcomp.pipeline.main.SentencePipeline.processBySentence(SentencePipeline.java:112)
        at edu.illinois.cs.cogcomp.pipeline.main.SentencePipeline.addView(SentencePipeline.java:88)
        at edu.illinois.cs.cogcomp.pipeline.main.SentencePipeline.addView(SentencePipeline.java:78)
zippedFileName: C:\Users\haijunxia\.cogcomp-datastore\tmp\4.0\ner-model-enron-conll-all-data.zip
path: C:\Users\haijunxia\.cogcomp-datastore\readonly.edu.illinois.cs.cogcomp.ner\4.0\ner-model-enron-conll-all-data
artifactId: ner-model-enron-conll-all-data
ERROR:ccg_nlpy.local_pipeline:Failed to add view SRL_VERB
ERROR:ccg_nlpy.local_pipeline:JVM exception occurred: View NER_CONLL not found
INFO:ccg_nlpy.core.text_annotation:The view is the collection of the following views: ['POS', 'SENTENCE', 'TOKENS']
Failed: Local Pipeline with Text
Local Tokenized SRL
ERROR:ccg_nlpy.local_pipeline:Failed to add view SRL_VERB
ERROR:ccg_nlpy.local_pipeline:JVM exception occurred: View NER_CONLL not found
INFO:ccg_nlpy.core.text_annotation:The view is the collection of the following views: ['POS', 'SENTENCE', 'TOKENS']
Failed: Local Pipeline with Tokens

**Comment by chrisoutwright** [comment]
I also have this issue. In the [m2repo](https://cogcomp.seas.upenn.edu/m2repo/edu/illinois/cs/cogcomp/resources/gazetteers/) I cannot find gazetteers-list.txt, but the jar which has it inside.
