### ISSUE TITLE
  text_annotation = self.pipeline.createBasicTextAnnotation("", "", text) AttributeError: 'NoneType' object has no attribute 'createBasicTextAnnotation'

### ISSUE THREAD

**Issue by monajalal** [CogComp/cogcomp-nlpy#86]
What is the minimum working example of a code that I feed in a string and gives me the named entities?

```
from ccg_nlpy import local_pipeline

pipeline = local_pipeline.LocalPipeline()

d = "RT @HuffingtonPost BREAKING: Hillary Clinton wins #NVCaucus https://t.co/ZVCgIDvrX1"

doc = pipeline.doc(d)

if doc is not None:
    # do sth with it
    ner_view = doc.get_ner_conll
```

For above code, I get the following error:
```
$ python ccg_ner.py
WARNING:ccg_nlpy.pipeline_config:Models not found. To use pipeline locally, please refer the documentation for downloading models.
INFO:ccg_nlpy.pipeline_config:Using local pipeline
ERROR:ccg_nlpy.local_pipeline:Fail to load models, please check if your Java version is up to date.
Traceback (most recent call last):
  File "ccg_ner.py", line 7, in <module>
    doc = pipeline.doc(d)
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/ccg_nlpy/pipeline_base.py", line 36, in doc
    response = self.call_server(text, "TOKENS")
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/ccg_nlpy/local_pipeline.py", line 63, in call_server
    text_annotation = self.pipeline.createBasicTextAnnotation("", "", text)
AttributeError: 'NoneType' object has no attribute 'createBasicTextAnnotation'
```

**Comment by danyaljj** [comment]
Seems like you're missing the model files. Did you run `python -m ccg_nlpy download` before running your code?

**Comment by monajalal** [comment]
Any idea what could be fixed?
```
$ java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-b10)
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)
$ python ccg_test.py 
INFO:ccg_nlpy.pipeline_config:Using local pipeline
ERROR:ccg_nlpy.local_pipeline:Fail to load models, please check if your Java version is up to date.
Traceback (most recent call last):
  File "ccg_test.py", line 7, in <module>
    doc = pipeline.doc(d)
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/ccg_nlpy/pipeline_base.py", line 36, in doc
    response = self.call_server(text, "TOKENS")
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/ccg_nlpy/local_pipeline.py", line 63, in call_server
    text_annotation = self.pipeline.createBasicTextAnnotation("", "", text)
AttributeError: 'NoneType' object has no attribute 'createBasicTextAnnotation'
$ cat ccg_test.py 
from ccg_nlpy import local_pipeline

pipeline = local_pipeline.LocalPipeline()

d = "RT @HuffingtonPost BREAKING: Hillary Clinton wins #NVCaucus https://t.co/ZVCgIDvrX1"

doc = pipeline.doc(d)

if doc is not None:
    # do sth with it
    ner_view = doc.get_ner_conll

```

**Comment by GHLgh** [comment]
@danyaljj @monajalal The actual error message was omitted in the code and on my side, the error message is the following:
```
dlopen(/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/jre/lib/server/libjvm.dylib, 10): image not found
```
The JDK 9 Release remove the sub-directory "jre" and I believe that pyjnius still searching files in "jre" directory. A [workaround](https://github.com/joeferner/node-java/issues/411) is to create a symbolic link (to pretend there is "jre" directory):
```
cd $JAVA_HOME
sudo ln -s ./ jre
```
After using the workaround, another issue came out:
```
jnius.JavaException: JVM exception occurred: View 'å' cannot be provided by this AnnotatorService.
```
It seems like [the Python string doesn't get converted to Java string properly](https://github.com/kivy/pyjnius/issues/300), as suggested in the issue, this can be fixed by converting the string explicitly before passing it to APIs on Java side:
```Python
# In local_pipeline.py

# import Java String class along with other imported autoclasses
self.JString = autoclass('java.lang.String') 
# Convert the string into Java String before calling APIs on Java side, example:
self.pipeline.addView(text_annotation, self.JString(view.strip()))
# Previous implementation: self.pipeline.addView(text_annotation,view.strip())
```
After that, the example can be run properly:
```bash
python -i test.py
...
>>> print(ner_view)
NER_CONLL view: (PER Hillary Clinton) (ORG NVCaucus)
```

**Comment by monajalal** [comment]
Thanks for looking into this. At the moment, I don't have enough permission and our site admin will look into this. I will notify if it will help us or what further bugs we might get.

**Comment by KeyWeeUsr** [comment]
Hi, check the https://github.com/kivy/pyjnius/issues/300 and the newest `pyjnius` release again whether it fixed the issues for you. If not, open a new issue with detailed description and reproducible steps. :dango:
